config/routes.rb
Encore::Application.routes.draw do
  root 'welcome#index'

  resources :bands
  resources :reviews, path: 'concerts'
  resources :users

  get     'media'           => 'media#index', as: 'media_index'
  post    'media'           => 'media#create'
  get     'media/new'       => 'media#new',   as: 'new_media'
  get     'media/:id/edit'  => 'media#edit',  as: 'edit_media'
  patch   'media/:id'       => 'media#update'
  put     'media/:id'       => 'media#update'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/band.rb
class Band < ActiveRecord::Base
  has_many :reviews

  has_attached_file :avatar, styles: { medium: '300x300#', thumb: '100x100#' }, default_url: '/images/band-:style.png'

  validates :name, presence: true, uniqueness: true

  scope :latest, -> { order('id DESC') }
end

app/models/media.rb
class Media < ActiveRecord::Base
  belongs_to :source, polymorphic: true

  has_attached_file :image, styles: { medium: '300x300#', thumb: '100x100#' }, default_url: '/images/media-:style.png'

  validates :image, presence: true, unless: ->(m) { m.youtube? }
  validates :source, presence: true
  validates :title, presence: true

  def lightbox_link
    youtube? ? link : image.url(:original)
  end

  def youtube?
    link =~ /youtube/
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :band
  belongs_to :user
  has_one :ticket
  has_many :media, as: :source, class_name: '::Media'

  validates :title, presence: true
  validates :content, presence: true
  validates :rating, inclusion: { in: 1..5 }
  validates :user_id, presence: true
  validates :played_at, presence: true

  accepts_nested_attributes_for :ticket

  validates_associated :ticket
  validates_associated :band

  scope :latest, -> { order('id DESC') }
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :review

  has_attached_file :stub, styles: { medium: '300x100#', thumb: '100x33#' }, default_url: '/images/ticket-:style.png'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_many :bands, through: :reviews
  has_many :tickets

  has_attached_file :avatar, styles: { medium: '300x300#', thumb: '100x100#' }, default_url: '/images/user-:style.png'

  validates :screen_name, presence: true, uniqueness: true

  scope :latest, -> { order('id DESC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
    @band = Band.new(band_params)

    @band.save ? redirect_to(@band) : render(:new)
  end

  def edit
    render :new
  end

  def update
    band.update_attributes(band_params) ? redirect_to(band) : render(:edit)
  end

private

  def reviews
    band.reviews.page(params[:page]).per(5)
  end
  helper_method :reviews

  def band_params
    params.require(:band).permit(:name, :twitter, :web, :avatar)
  end

  def band
    @band ||= params[:id].present? ? Band.find(params[:id]) : Band.new
  end
  helper_method :band

  def bands
    @bands ||= Band.latest.page(params[:page])
  end
  helper_method :bands

end

app/controllers/media_controller.rb
class MediaController < ApplicationController

  def new
  end

  def create
    @media = Media.new(media_params)
    @media.save ? redirect_to(media.source) : render(:new)
  end

  def edit
  end

  def update
    media.attributes = media_params
    media.save ? redirect_to(media.source) : render(:edit)
  end

private

  def media_params
    params.require(:media).permit(:source_id, :source_type, :title, :link, :image)
  end

  def media
    @media ||= params[:id].present? ? Media.find(params[:id]) : Media.new(params.permit(:source_id, :source_type))
  end
  helper_method :media

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
    @review = Review.new(review_params)
    @review.band = Band.where(name: params[:band][:name].squish).first_or_initialize

    @review.save ? redirect_to(@review) : render(:new)
  end

  def edit
  end

  def update
    review.band = Band.where(name: params[:band][:name].squish).first_or_initialize
    review.attributes = review_params
    review.save ? redirect_to(@review) : render(:edit)
  end

private

  def review_params
    params[:review][:ticket_attributes][:user_id] = params[:review][:user_id]
    params.require(:review).permit(
      :title, :content, :rating, :user_id, :played_at, :venue,
      ticket_attributes: [:id, :user_id, :event_code, :section, :row, :seat, :stub]
    )
  end

  def review
    @review ||= begin
      r = params[:id].present? ? Review.find(params[:id]) : Review.new(params.permit(:user_id))
      r.ticket ||= Ticket.new
      r
    end
  end
  helper_method :review

  def band
    @band = review.band || Band.new
  end
  helper_method :band

  def media
    @media ||= review.media
  end
  helper_method :media

  def reviews
    @reviews ||= Review.latest.page(params[:page])
  end
  helper_method :reviews

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
    @user = User.new(user_params)

    @user.save ? redirect_to(@user) : render(:new)
  end

  def edit
  end

  def update
    user.update_attributes(user_params) ? redirect_to(user) : render(:edit)
  end

private

  def reviews
    user.reviews.page(params[:page]).per(5)
  end
  helper_method :reviews

  def user_params
    params.require(:user).permit(:screen_name, :avatar)
  end

  def user
    @user ||= params[:id].present? ? User.find(params[:id]) : User.new
  end
  helper_method :user

  def users
    @users ||= User.latest.page(params[:page])
  end
  helper_method :users

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

private

  def users
    @users ||= User.latest.page(params[:page]).per(8)
  end
  helper_method :users

  def reviews
    @reviews ||= Review.latest.page(params[:page]).per(8)
  end
  helper_method :reviews

  def bands
    @bands ||= Band.latest.page(params[:page]).per(8)
  end
  helper_method :bands

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper

  def twitter_link(band)
    return unless band.twitter.present?

    link_to 'twitter', "http://twitter.com/#{band.twitter}"
  end

  def website_link(band)
    return unless band.web.present?

    link_to 'website', band.web
  end

end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def paragraphs(content)
    content.split(/\r?\n/).reject(&:blank?).map { |p| content_tag(:p, h(p)) }.join.html_safe
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bands/_band.html.erb
<div class="band">
  <%= link_to_unless_current image_tag(band.avatar.url(:thumb)), band %>
  <h1><%= link_to_unless_current band.name, band %></h1>
  <p><%= [twitter_link(band), website_link(band)].compact.join(' | ').html_safe %></p>
  <p><%= link_to_unless_current "#{band.reviews.count} #{'review'.pluralize(band.reviews.count)}", band %></p>
</div>

app/views/bands/_form.html.erb
<%= form_for band, html: { multipart: true } do |f| %>

  <table>
    <tr>
      <td>
        <%= f.label :name %> <span class="error"><%= band.errors[:name].join(', ') %></span><br />
        <%= f.text_field :name %><br />
        <%= f.label :twitter, 'Twitter Account Name' %><br />
        <%= f.text_field :twitter %><br />
        <%= f.label :web, 'Website' %><br />
        <%= f.text_field :web %>
      </td>
      <td>&nbsp;</td>
      <td>
        <%= image_tag band.avatar.url(:thumb) %><br />
        <%= f.label :avatar, 'Change Avatar' %><br />
        <%= f.file_field :avatar %>
      </td>
    </tr>
    <tr><td colspan="3"><%= f.submit %></td></tr>
  </table>

<% end %>

app/views/bands/edit.html.erb
<% content_for(:title) { 'Edit Band' } %>

<h1>Edit Band</h1>

<%= render 'form' %>

app/views/bands/index.html.erb
<h1>Bands</h1>

<p><%= link_to 'Create Band', new_band_path %></p>

<% bands.each do |band| %>
  <%= render band %>
<% end %>

<%= paginate bands %>

app/views/bands/new.html.erb
<% content_for(:title) { 'Create a Band' } %>

<h1>Create a Band</h1>

<%= render 'form' %>

app/views/bands/show.html.erb
<h1><%= band.name %></h1>

<%= render band %>

<p><%= link_to 'Edit Profile', edit_band_path(band) %>

<h1>Reviews</h1>

<%= render reviews %>

<%= paginate reviews %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Noto+Serif' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Noto+Sans' rel='stylesheet' type='text/css'>

  <title>Encore! A personal journal of live events.</title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <link href="/favicon.ico" rel="shortcut icon" type="image/x-icon" />
</head>
<body>

<%= yield %>

  <script>
    $.fn.raty.defaults.hints = ['bad', 'poor', 'okay', 'good', 'great'];
    $.each($('.stars'), function(index, object) {
      var elm = $(object);
      elm.empty();
      elm.raty({
        readOnly: true,
        score: elm.data('number'),
        path: '/images'
      });
    });
    $(document).ready(function() {
      $('.fancybox').fancybox();
      $('.youtube').fancybox({
        maxWidth    : 800,
        maxHeight   : 600,
        fitToView   : false,
        width       : '70%',
        height      : '70%',
        autoSize    : false,
        closeClick  : false,
        openEffect  : 'none',
        closeEffect : 'none'
      });
    });
  </script>
  <script src="http://s0.railsrumble.com/banner.js" type="text/javascript"></script>

</body>
</html>

app/views/layouts/bands.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Noto+Serif' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Noto+Sans' rel='stylesheet' type='text/css'>

  <title>Encore! <%= content_for(:title) || band.try(:name) || 'Bands' %></title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <link href="/favicon.ico" rel="shortcut icon" type="image/x-icon" />
</head>
<body>

  <div id="container">
    <p><%= link_to 'Reviews', reviews_path %> | <%= link_to 'Users', users_path %> | <%= link_to 'Bands', bands_path %></p>
    <%= link_to image_tag('encore-plain.png', alt: 'Encore! A personal journal of live events.', id: 'welcome-logo'), root_url %>

<%= yield %>

  </div>

  <script>
    $.fn.raty.defaults.hints = ['bad', 'poor', 'okay', 'good', 'great'];
    $.each($('.stars'), function(index, object) {
      var elm = $(object);
      elm.empty();
      elm.raty({
        readOnly: true,
        score: elm.data('number'),
        path: '/images'
      });
    });
    $(document).ready(function() {
      $('.fancybox').fancybox();
      $('.youtube').fancybox({
        maxWidth    : 800,
        maxHeight   : 600,
        fitToView   : false,
        width       : '70%',
        height      : '70%',
        autoSize    : false,
        closeClick  : false,
        openEffect  : 'none',
        closeEffect : 'none'
      });
    });
  </script>

</body>
</html>

app/views/layouts/media.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Noto+Serif' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Noto+Sans' rel='stylesheet' type='text/css'>

  <title>Encore! <%= content_for(:title) || media.try(:title) || 'Media' %></title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <link href="/favicon.ico" rel="shortcut icon" type="image/x-icon" />
</head>
<body>

  <div id="container">
    <p><%= link_to 'Reviews', reviews_path %> | <%= link_to 'Users', users_path %> | <%= link_to 'Bands', bands_path %></p>
    <%= link_to image_tag('encore-plain.png', alt: 'Encore! A personal journal of live events.', id: 'welcome-logo'), root_url %>

<%= yield %>

  </div>

  <script>
    $.fn.raty.defaults.hints = ['bad', 'poor', 'okay', 'good', 'great'];
    $.each($('.stars'), function(index, object) {
      var elm = $(object);
      elm.empty();
      elm.raty({
        readOnly: true,
        score: elm.data('number'),
        path: '/images'
      });
    });
    $(document).ready(function() {
      $('.fancybox').fancybox();
      $('.youtube').fancybox({
        maxWidth    : 800,
        maxHeight   : 600,
        fitToView   : false,
        width       : '70%',
        height      : '70%',
        autoSize    : false,
        closeClick  : false,
        openEffect  : 'none',
        closeEffect : 'none'
      });
    });
  </script>

</body>
</html>

app/views/layouts/reviews.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Noto+Serif' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Noto+Sans' rel='stylesheet' type='text/css'>

  <title>Encore! <%= content_for(:title) || review.try(:title) || 'Concerts' %></title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <link href="/favicon.ico" rel="shortcut icon" type="image/x-icon" />
</head>
<body>

  <div id="container">
    <p><%= link_to 'Reviews', reviews_path %> | <%= link_to 'Users', users_path %> | <%= link_to 'Bands', bands_path %></p>
    <%= link_to image_tag('encore-plain.png', alt: 'Encore! A personal journal of live events.', id: 'welcome-logo'), root_url %>

<%= yield %>

  </div>

  <script>
    $.fn.raty.defaults.hints = ['bad', 'poor', 'okay', 'good', 'great'];
    $.each($('.stars'), function(index, object) {
      var elm = $(object);
      elm.empty();
      elm.raty({
        readOnly: true,
        score: elm.data('number'),
        path: '/images'
      });
    });
    $(document).ready(function() {
      $('.fancybox').fancybox();
    });
  </script>

</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Noto+Serif' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Noto+Sans' rel='stylesheet' type='text/css'>

  <title>Encore! <%= content_for(:title) || user.try(:screen_name) || 'Users' %></title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <link href="/favicon.ico" rel="shortcut icon" type="image/x-icon" />
</head>
<body>

  <div id="container">
    <p><%= link_to 'Reviews', reviews_path %> | <%= link_to 'Users', users_path %> | <%= link_to 'Bands', bands_path %></p>
    <%= link_to image_tag('encore-plain.png', alt: 'Encore! A personal journal of live events.', id: 'welcome-logo'), root_url %>

<%= yield %>

  </div>

  <script>
    $.fn.raty.defaults.hints = ['bad', 'poor', 'okay', 'good', 'great'];
    $.each($('.stars'), function(index, object) {
      var elm = $(object);
      elm.empty();
      elm.raty({
        readOnly: true,
        score: elm.data('number'),
        path: '/images'
      });
    });
    $(document).ready(function() {
      $('.fancybox').fancybox();
      $('.youtube').fancybox({
        maxWidth    : 800,
        maxHeight   : 600,
        fitToView   : false,
        width       : '70%',
        height      : '70%',
        autoSize    : false,
        closeClick  : false,
        openEffect  : 'none',
        closeEffect : 'none'
      });
    });
  </script>

</body>
</html>

app/views/media/_form.html.erb
<%= form_for media do |f| %>

  <%= f.hidden_field :source_id %>
  <%= f.hidden_field :source_type %>

  <%= f.label :title %> <span class="error"><%= media.errors[:title].join(', ') %></span><br />
  <%= f.text_field :title %><br />

  <%= f.label :link %> <span class="error"><%= media.errors[:link].join(', ') %></span><br />
  <%= f.text_field :link %> (Reference or YouTube Embed Links)<br />

  <table>
    <tr>
      <td><%= image_tag media.image.url(:thumb) %></td>
      <td>&nbsp;</td>
      <td><%= f.label :image, 'Change Image' %> <span class="error"><%= media.errors[:image].join(', ') %></span><br />
          <%= f.file_field :image %>
      </td>
    </tr>
  </table>

  <%= f.submit %>
<% end %>

app/views/media/_media.html.erb
<div class="media">
  <%= link_to image_tag(media.image(:thumb)), media.lightbox_link, class: "fancybox#{'.iframe youtube' if media.youtube?}", rel: 'media' %>
  <p><%= link_to_if((media.link && !media.youtube?), media.title, media.link) %></p>
</div>

app/views/media/edit.html.erb
<% content_for(:title) { 'Edit Media' } %>

<h1>Edit Media</h1>

<%= render 'form' %>

app/views/media/new.html.erb
<% content_for(:title) { 'Attach Media' } %>

<h1>Attach Media</h1>

<%= render 'form' %>

app/views/reviews/_form.html.erb
<%= form_for review do |f| %>

    <%= f.label :title %> <span class="error"><%= review.errors[:title].join(', ') %></span><br />
    <%= f.text_field :title %><br />

  <%= fields_for band do |b| %>
    <%= b.label :name, 'Band' %> <span class="error"><%= band.errors[:name].join(', ') %></span><br />
    <%= b.text_field :name %><br />
  <% end %>

  <%= f.label :venue %><br />
  <%= f.text_field :venue %><br />

  <%= f.label :played_at, 'Day of the Concert' %> <span class="error"><%= review.errors[:played_at].join(', ') %></span><br />
  <%= f.date_field :played_at %><br />

  <%= f.label :content %> <span class="error"><%= review.errors[:content].join(', ') %></span><br />
  <%= f.text_area :content %><br />

  <%= f.label :rating %> <span class="error"><%= review.errors[:rating].join(', ') %></span><br />
  <span id="star"></span><%= f.hidden_field :rating %><br />

  <%= f.label :user_id %> <span class="error"><%= review.errors[:user_id].join(', ') %></span><br />
  <%= f.select :user_id, User.all.map {|u| [u.screen_name, u.id] }, include_blank: true %><br /><br />

  <%= f.fields_for :ticket do |t| %>
    <fieldset>
      <legend>Ticket Stub</legend>

      <table>
        <tr>
          <td><%= image_tag review.ticket.stub.url(:thumb) %></td>
          <td>&nbsp;</td>
          <td><%= t.label :stub, 'Change Stub' %><br />
              <%= t.file_field :stub %>
          </td>
        </tr>
      </table>

      <table>
        <tr>
          <td><%= t.label :event_code %><br />
              <%= t.text_field :event_code %>
          </td>
          <td>&nbsp;</td>
          <td><%= t.label :section %><br />
              <%= t.text_field :section %>
          </td>
        </tr>
        <tr>
          <td><%= t.label :row %><br />
              <%= t.text_field :row %>
          </td>
          <td>&nbsp;</td>
          <td><%= t.label :seat %><br />
              <%= t.text_field :seat %>
          </td>
        </tr>
      </table>
    </fieldset><br />
  <% end %>

  <%= f.submit %>
<% end %>

<script>
  $('#star').raty({
    path      : '/images',
    score     : '<%= review.rating %>',
    target    : '#review_rating',
    targetType: 'number',
    targetKeep: true
  });
</script>

app/views/reviews/_review.html.erb
<div class="review">

  <%= link_to_unless_current image_tag(review.band.avatar.url(:thumb)), review.band %><br />
  <span class="stars" data-number="<%= review.rating %>"><%= review.rating %> Stars</span>

  <h1><%= link_to truncate(review.title, length: 50, separator: ' '), review %></h1>

</div>

app/views/reviews/edit.html.erb
<% content_for(:title) { 'Edit Review' } %>

<h1>Edit Review</h1>

<%= render 'form' %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<p><%= link_to 'Create Review', new_review_path %></p>

<%= render reviews %>

<%= paginate reviews %>

app/views/reviews/new.html.erb
<% content_for(:title) { 'Create a Review' } %>

<h1>Create a Review</h1>

<%= render 'form' %>

app/views/reviews/show.html.erb
<% if review.ticket.stub.present? %>
<%= link_to image_tag(review.ticket.stub(:medium), class: 'stub'), review.ticket.stub(:original), class: 'fancybox' %>
<% end %>

<h1><%= review.title %></h1>
<h2><%= review.venue %> (<%= review.played_at.to_s(:long) %>)</h2>
<h3>by <%= review.user.screen_name %></h3>

<%= paragraphs(review.content) %>

<div class="stars" data-number="<%= review.rating %>"><%= review.rating %> Stars</div>

<% if media.any? %>
<h2>Associated Media</h2>

<%= render media %>

<% end %>

<p><%= link_to 'Edit Review', edit_review_path(review) %> | <%= link_to 'Attach Media', new_media_path(source_id: review.id, source_type: 'Review') %></p>

app/views/users/_form.html.erb
<%= form_for user, html: { multipart: true } do |f| %>

  <%= f.label :screen_name %> <span class="error"><%= user.errors[:screen_name].join(', ') %></span><br />
  <%= f.text_field :screen_name %><br /><br />
  <%= image_tag user.avatar.url(:thumb) %><br />
  <%= f.label :avatar, 'Change Avatar' %><br />
  <%= f.file_field :avatar %><br /><br />
  <%= f.submit %>

<% end %>

app/views/users/_user.html.erb
<div class="user">
  <%= link_to_unless_current image_tag(user.avatar.url(:thumb)), user %><br />
  <h1><%= link_to_unless_current user.screen_name, user %></h1>
  <p><%= user.reviews.count %> <%= 'review'.pluralize(user.reviews.count) %></p>
</div>

app/views/users/edit.html.erb
<% content_for(:title) { 'Edit User' } %>

<h1>Edit User</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>

<p><%= link_to 'Create User', new_user_path %></p>

<%= render users %>

<%= paginate users %>

app/views/users/new.html.erb
<% content_for(:title) { 'Create a User' } %>

<h1>Create a User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= user.screen_name %></h1>

<%= render user %>

<p><%= link_to 'Edit Profile', edit_user_path(user) %> | <%= link_to 'Write a Review', new_review_path(user_id: user.id) %></p>

<h1>Reviews</h1>

<%= render reviews %>

<%= paginate reviews %>

app/views/welcome/index.html.erb
<%= image_tag 'encore.png', alt: 'Encore! A personal journal of live events.', id: 'welcome-logo' %>

<h1>Recent Reviews</h1>

<div id="reviews" class="clearfix">
  <%= render reviews %>
</div>

<p><%= link_to 'All Reviews', reviews_path %> | <%= link_to 'Write a Review', new_review_path %></p>

<h1>Recent Users</h1>

<div id="users" class="clearfix">
  <%= render users %>
</div>

<p><%= link_to 'All Users', users_path %> | <%= link_to 'Create a User', new_user_path %></p>

<h1>Recent Bands</h1>

<div id="bands" class="clearfix">
  <%= render bands %>
</div>

<p><%= link_to 'All Bands', bands_path %> | <%= link_to 'Create a Band', new_band_path %></p>